anchor_version = "0.20.1"
solana_version = "1.9.0"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
merkle_distributor = "PMRKTWvK9f1cPkQuXvvyDPmyCSoq8FdedCimXrXJp8M"

[programs.devnet]
merkle_distributor = "PMRKTWvK9f1cPkQuXvvyDPmyCSoq8FdedCimXrXJp8M"

[programs.testnet]
merkle_distributor = "PMRKTWvK9f1cPkQuXvvyDPmyCSoq8FdedCimXrXJp8M"

[programs.localnet]
merkle_distributor = "PMRKTWvK9f1cPkQuXvvyDPmyCSoq8FdedCimXrXJp8M"

[scripts]
test = "yarn mocha"
